##     numpy prac_1( 5-11-22)


### Himanshu G Marekar
### D-41

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [5]:
#import numpy as np
arr=np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [8]:
a=[100,200,300]
b=[400,500,600]
c=[50,50,50]

a+c+b

[100, 200, 300, 50, 50, 50, 400, 500, 600]

In [9]:
np_arr1=np.array(a)
np_arr2=np.array(b)
np_arr3=np.array(c)
print(np_arr1,np_arr2,np_arr3)

[100 200 300] [400 500 600] [50 50 50]


In [10]:
print(np_arr1+np_arr2+np_arr3)

[550 750 950]


In [11]:
np_arr1+1000

array([1100, 1200, 1300])

In [12]:
np_arr1[np_arr1 >100]

array([200, 300])

In [13]:
print(np_arr1>100)

[False  True  True]


### numpy arr using tuple and list

In [14]:
a=[1,2,3,4,5]
arr=np.array(a)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
a=(1,2,3,4,5)
arr=np.array(a)
print(type(arr))
type(a)

<class 'numpy.ndarray'>


tuple

In [29]:
x=[[[1,2,3],[4,5,6]],[[7,6,8],[12,11,23]]]
a = np.array(x)
print(a) 
print(type(arr)) 
print(a.ndim)
#print(arr[0:3,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  6  8]
  [12 11 23]]]
<class 'numpy.ndarray'>
3


In [20]:
a[-1]

array([[ 7,  6,  8],
       [12, 11, 23]])

In [24]:
print(a[-2].ndim)
a[0:2,1]

2


array([[ 4,  5,  6],
       [12, 11, 23]])

### higher dim

In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [36]:
print(arr[2,1:-1])
print(arr[:3])

[8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#arr.ndim
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [39]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [41]:
arr1 = np.array([[1,1,1],[2,2,2]])
arr2 = np.array([[3,1,4],[2,5,2]])
arr1*arr2

array([[ 3,  1,  4],
       [ 4, 10,  4]])

### numpy joining array

In [4]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.concatenate((a1,a2))
print(arr,arr.ndim)
len(arr)

[1 2 3 4 5 6] 1


6

In [6]:
a1=np.array([[1,2,3],[7,8,9]])
a2=np.array([[4,5,6],[5,1,2]])
arr=np.concatenate((a1,a2),axis=1) #colm combine
print(arr,arr.ndim)

[[1 2 3 4 5 6]
 [7 8 9 5 1 2]] 2


In [7]:
arr=np.concatenate((a1,a2),axis=0) #row
print(arr,arr.ndim)

[[1 2 3]
 [7 8 9]
 [4 5 6]
 [5 1 2]] 2


### stack() func

In [14]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.hstack((a1,a2)) #h fr hori
arr1=np.vstack((a1,a2))#v fr verti
arr2=np.dstack((a1,a2)) # d fr dim  index stack
print(arr)
print(arr1)
print(arr2,arr2.ndim)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]] 3


### numpy split data

In [27]:
arr=np.array([[1,2,3],[4,5,6],[8,9,1]])
narr=np.array_split(arr,2)  
print(narr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[8, 9, 1]])]


In [25]:
arr=np.array([[1,2,3],[4,5,6],[8,9,1],[2,3,4],[5,3,2]])
narr=np.array_split(arr,3,axis=1)  
print(narr)

[array([[1],
       [4],
       [8],
       [2],
       [5]]), array([[2],
       [5],
       [9],
       [3],
       [3]]), array([[3],
       [6],
       [1],
       [4],
       [2]])]


### searching arr

In [28]:
arr=np.array([1,2,3,4,5,6,8,9,1])
a=np.where(arr>3) #index posn
print(a)

(array([3, 4, 5, 6, 7], dtype=int64),)


In [29]:
arr=np.array([1,2,3,4,5,6,8,9,1])
a=np.where(arr%2==0) 
print(a)

(array([1, 3, 5, 6], dtype=int64),)


###sort

In [30]:
arr=np.array([1,2,3,4,5,6,8,9,1])
a=np.sort(arr) 
print(a)

[1 1 2 3 4 5 6 8 9]


In [32]:
arr=np.array(['cr','ggs','xdd','ggwp'])
a=np.sort(arr) 
print(a)

['cr' 'ggs' 'ggwp' 'xdd']


In [38]:
arr=np.array([[1,3,2],[5,4,6],[8,9,1]]) #sort ind arr
a=np.sort(arr)                           #(arr size should be same)
print(a)

[[1 2 3]
 [4 5 6]
 [1 8 9]]


### filter arr

In [40]:
arr=np.array([41,44,43,42])
x=[True,False,True,True]
nearr=arr[arr>41]
narr=arr[x]
print(narr)
print(nearr)

[41 43 42]
[44 43 42]


In [ ]:
#self
arr=[]
n=int(input("etr n\n : "))
for i in range(0,n):
    elem=int(input())
    arr.append(elem)
print(arr)
# arr=arr[arr%2==0]
# arr

In [46]:
arr=np.array([1,2,3,4,5,6,7])
flt_lst=[]
for elem in arr:
    if elem %2==0:
        flt_lst.append(True)
    else:
        flt_lst.append(False)
print(flt_lst)
narr=arr[flt_lst]
narr

[False, True, False, True, False, True, False]


array([2, 4, 6])

#### matrix multi by numpy 2-D

In [1]:
#matrix multiplication

"""
import numpy as np


mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
res = mat1 @ mat2
print(res)
"""

# We need install numpy in order to import it
import numpy as np

# input two matrices
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

# This will return dot product
res = np.dot(mat1,mat2)


# print resulted matrix
print(res)


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
